repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: pretty-format-json

  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
        -   id: isort
            files: \.py$
            args: ['--profile', 'black']

  -   repo: https://github.com/psf/black
      rev: 24.2.0
      hooks:
        -   id: black
            language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
